apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: ad-demo-vnet
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: "West US 2"
    resourceGroupName: rg-crossplane-test