apiVersion: network.azure.crossplane.io/v1alpha3
kind: VirtualNetwork
metadata:
  name: ad-demo-vnet
spec:
  location: West US 2
  properties:
    addressSpace:
      addressPrefixes:
        - 10.2.0.0/16
  providerConfigRef:
    name: default
  resourceGroupNameRef:
    name: ad-demo-rg